### PR TITLE
ENQT-236-remove-plus-button-from-pagetree

### PR DESCRIPTION
**Pull request by alessioscalici**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by nicpuddu** [comment]
@alessioscalici please solve the conflicts

**Comment by alessioscalici** [comment]
Apparently, after I fixed the conflicts, the change is not there anymore, somebody took care of the same thing, leaving to this PR an indentation change. Feel free to merge it or leave it as is

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by DMinnai** [comment]
I took care of it yesterday morning @alessioscalici  :)
i think it should be leaved as it is right now and maybe deleting about deleting it later on.

**Pull request merged**
