### PR TITLE
EN-2422 Fix bug on Logger

### PR DESCRIPTION
**Pull request by eugeniosant**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by pietrangelo** [comment]
@eugeniosant Doesn't work as expected. Logs are written only after i close the java container and only a part of them. Tested with jetty on Windows platform

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Pull request merged**
