### PR TITLE
Enqt 130 bis

### PR DESCRIPTION
**Pull request by FabioFortini**

### CODE REVIEW

**Comment by entando-service** [comment]
Can one of the admins verify this patch?

**Comment by nicpuddu** [comment]
test this please

**Comment by nicpuddu** [comment]
please test this

**Comment by nicpuddu** [comment]
add to whitelist

**Comment by nicpuddu** [comment]
test this please

**Comment by entando-service** [comment]
add to whitelist

**Comment by entando-service** [comment]
All is well

**Pull request merged**
