### PR TITLE
 EN-1857-read-and-save-metadata-on-images-in-multiple-uploader

### PR DESCRIPTION
**Pull request by alepintus**
Hey @joewhite101 @eugeniosant ,
This commit is for resource metadata task.

It should be merged a the same time with the entando-components and entando-archetypes PR below:

https://github.com/entando/entando-components/pull/304
https://github.com/entando/entando-archetypes/pull/66

Thanks!

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by alepintus** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by pietrangelo** [comment]
retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
