### PR TITLE
EN-2407 Changed password encoding to bcrypt + refactoring

### PR DESCRIPTION
**Pull request by zonia3000**
**Warning**: this PR will break components. Ensure that the [corresponding changes in components](https://github.com/entando/entando-components/tree/EN-2407) have been tested before merging.

Changes in this PR:

- Interface [IApsEncrypter](https://github.com/entando/entando-core/blob/master/engine/src/main/java/com/agiletec/aps/util/IApsEncrypter.java) has been removed and Spring interfaces `TextEncryptor` and `PasswordEncoder` have been used instead.
- Encryption related classes have been moved into a dedicated package: `org.entando.entando.aps.util.crypto`
- BCrypt is used instead of Argon2 for hashing the new user passwords. Existing users having password encoded using Argon2 can still be used (this is done by the [CompatiblePasswordEncoder](https://github.com/entando/entando-core/blob/06da6e8e2dcbbf9f7cc9218524155b8a3e449fd1/engine/src/main/java/org/entando/entando/aps/util/crypto/CompatiblePasswordEncoder.java) class).
- Utility class [XMLFieldsEncryptor](https://github.com/entando/entando-core/blob/06da6e8e2dcbbf9f7cc9218524155b8a3e449fd1/engine/src/main/java/org/entando/entando/aps/util/crypto/EncryptorAdapter.java) able to encrypt specific fields during JAXB serialization has been added. This can be useful for encrypting sensitive data stored in XML format in a transparent way
- General refactoring of old code removing also the [MockUser](https://github.com/entando/entando-core/blob/master/engine/src/test/java/com/agiletec/aps/system/services/user/MockUser.java) class.

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by zonia3000** [comment]
I've created the [related PR in components](https://github.com/entando/entando-components/pull/495).

**Comment by entando-service** [comment]
All is well

**Pull request merged**
