### PR TITLE
ENG-283 change labels

### PR DESCRIPTION
**Pull request by ichalagashvili**
PR for: https://jira.entando.org/browse/ENG-283
Changing:
- "page model" labels to "page template"
- "content model" labels to "content template"
- "digital exchange" to "component repository

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Pull request closed without merging**
