### PR TITLE
En 1630 fix user profile aspect

### PR DESCRIPTION
**Pull request by eugeniosant**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by eugeniosant** [comment]
Added unit tests for class UserProfileManagerAspect.java. Test for aspectj (for jcache) are also in class UserProfileManagerIntegrationTest.class

**Comment by entando-service** [comment]
All is well

**Pull request merged**
