### PR TITLE
EN6-144 implemented list view pages API endpoint

### PR DESCRIPTION
**Pull request by ffleandro**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by eugeniosant** [comment]
I don't understand why this functionality is placed into the core if it is intended for the cms plugin, in particular for the configation of the content types

**Comment by ffleandro** [comment]
@eugeniosant I created it on the core because it's a list of `Pages` with a specific configuration and `Page` is a core entity.
Although unlikely, other plugins may also need this functionality.

**Comment by ffleandro** [comment]
@joewhite101 
I didn't create PageUtils, it was something that already existed on the CMS.
I just separated Core PageUtils from CMS PageUtils

**Pull request merged**
