### PR TITLE
Enqt 242

### PR DESCRIPTION
**Pull request by fedelocci**
UX Pattern - FE - fix bug grafici

### CODE REVIEW

**Comment by entando-service** [comment]
Can one of the admins verify this patch?

**Comment by fedelocci** [comment]
ENQT 243, ENQT 244, ENQT 245, ENQT 246, ENQT 247, ENQT 248

**Comment by nicpuddu** [comment]
add to whitelist

**Comment by nicpuddu** [comment]
test this please

**Comment by nicpuddu** [comment]
test this please

**Pull request closed without merging**
