### PR TITLE
En 1747 multi group select for pages

### PR DESCRIPTION
**Pull request by joewhite101**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by joewhite101** [comment]
@DMinnai can you review Eugenio's note and take a look?

**Comment by DMinnai** [comment]
Actually on chrome it is working flawlessly as the problem occurs only on firefox.

**Comment by entando-service** [comment]
All is well

**Comment by DMinnai** [comment]
now confirmed working on safari and firefox. It can be merged

**Comment by joewhite101** [comment]
@eugeniosant  can you review/merge again? davide fixed the firefox stuff.

**Pull request merged**
