### PR TITLE
EN-2511 EN-2512 Removed support for Argon2, moved default TextEncryptor in components

### PR DESCRIPTION
**Pull request by zonia3000**
See also related PR in components: https://github.com/entando/entando-components/pull/513

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by joewhite101** [comment]
Overcome by events

**Pull request closed without merging**
