### PR TITLE
En-1608-ckeditor-upgrade

### PR DESCRIPTION
**Pull request by alepintus**
Hi @joewhite101 , @eugeniosant ,
CKEditor updated to version 4.9 and new entandolink plugin implementation

Could you please have a look?
Thanks!

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by joewhite101** [comment]
Hey @alepintus is there a way to include the CK editor as a dependency without dropping the entire codebase inside of our project as source?

**Comment by alepintus** [comment]
Hey @joewhite101 , 
I checked the documentation and with CKEditor 4 we can only copy the folder or add a link to cdn to load the js. Only from CKEditor 5 the builds are released on npm and with the next upgrade we can load the lib from there.

Thanks!

**Comment by entando-service** [comment]
All is well

**Pull request merged**
